### ISSUE TITLE
Optional filter parameters in `AND` `OR` logical operations

### ISSUE THREAD

**Issue by Noezor** [typedorm/typedorm#307]
👋 , thanks for the great project!

I am trying to update to 1.15+ following https://github.com/typedorm/typedorm/issues/142 but my filter which worked on 1.14 does not work on 1.15 anymore trying to build the logical operator filter argument by argument

Some sample code:

```
    public async queryStudent(state: string, school: string, age?: number): any {
    const filter: FilterOptions<StudentModel, StatePriorityIndex> = {
      AND: {
        school: {
          EQ: school,
        },
      },
    };

    if (age) { // error is here
      filter.AND.age = {
        EQ: age,
      };
    }

    const options: EntityManagerFindOptions<TaskExecutionModel, StatePriorityIndex> = {
        queryIndex: this.stateIndex,
        where: filter,
      };

    return await this.entityManager.find<StudentModel, StateIndex>(
      TaskExecutionModel,
      { state },
      options
    );
  }
```

It fails with a throw
```
Property 'stuedent_age' does not exist on type '{} | Partial<AttributeFilterOptions<StudentModel, ResourceUuidPriorityIndex> & RecursiveFilterOptions<StudentModel, ResourceUuidPriorityIndex>>'.
```

How would you advise doing such filter on `1.15`?
